/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Tracks;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LocalDateTime extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5663823583798384471L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocalDateTime\",\"namespace\":\"Tracks\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LocalDateTime> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LocalDateTime> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LocalDateTime> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LocalDateTime> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LocalDateTime> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LocalDateTime to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LocalDateTime from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LocalDateTime instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LocalDateTime fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }


  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Creates a new LocalDateTime RecordBuilder.
   * @return A new LocalDateTime RecordBuilder
   */
  public static Tracks.LocalDateTime.Builder newBuilder() {
    return new Tracks.LocalDateTime.Builder();
  }

  /**
   * Creates a new LocalDateTime RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LocalDateTime RecordBuilder
   */
  public static Tracks.LocalDateTime.Builder newBuilder(Tracks.LocalDateTime.Builder other) {
    if (other == null) {
      return new Tracks.LocalDateTime.Builder();
    } else {
      return new Tracks.LocalDateTime.Builder(other);
    }
  }

  /**
   * Creates a new LocalDateTime RecordBuilder by copying an existing LocalDateTime instance.
   * @param other The existing instance to copy.
   * @return A new LocalDateTime RecordBuilder
   */
  public static Tracks.LocalDateTime.Builder newBuilder(Tracks.LocalDateTime other) {
    if (other == null) {
      return new Tracks.LocalDateTime.Builder();
    } else {
      return new Tracks.LocalDateTime.Builder(other);
    }
  }

  /**
   * RecordBuilder for LocalDateTime instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocalDateTime>
    implements org.apache.avro.data.RecordBuilder<LocalDateTime> {


    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Tracks.LocalDateTime.Builder other) {
      super(other);
    }

    /**
     * Creates a Builder by copying an existing LocalDateTime instance
     * @param other The existing instance to copy.
     */
    private Builder(Tracks.LocalDateTime other) {
      super(SCHEMA$, MODEL$);
    }

    @Override
    @SuppressWarnings("unchecked")
    public LocalDateTime build() {
      try {
        LocalDateTime record = new LocalDateTime();
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LocalDateTime>
    WRITER$ = (org.apache.avro.io.DatumWriter<LocalDateTime>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LocalDateTime>
    READER$ = (org.apache.avro.io.DatumReader<LocalDateTime>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
    } else {
      for (int i = 0; i < 0; i++) {
        switch (fieldOrder[i].pos()) {
        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










